// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: status.proto

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HTTPStatus    int32                  `protobuf:"varint,1,opt,name=HTTPStatus,json=http_status,proto3" json:"HTTPStatus,omitempty"`
	ProcessTime   string                 `protobuf:"bytes,2,opt,name=ProcessTime,json=process_time,proto3" json:"ProcessTime,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseSuccess) Reset() {
	*x = ResponseSuccess{}
	mi := &file_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSuccess) ProtoMessage() {}

func (x *ResponseSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSuccess.ProtoReflect.Descriptor instead.
func (*ResponseSuccess) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseSuccess) GetHTTPStatus() int32 {
	if x != nil {
		return x.HTTPStatus
	}
	return 0
}

func (x *ResponseSuccess) GetProcessTime() string {
	if x != nil {
		return x.ProcessTime
	}
	return ""
}

func (x *ResponseSuccess) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_status_proto protoreflect.FileDescriptor

const file_status_proto_rawDesc = "" +
	"\n" +
	"\fstatus.proto\x12\aruntime\x1a\x1cgoogle/protobuf/struct.proto\"\x82\x01\n" +
	"\x0fResponseSuccess\x12\x1f\n" +
	"\n" +
	"HTTPStatus\x18\x01 \x01(\x05R\vhttp_status\x12!\n" +
	"\vProcessTime\x18\x02 \x01(\tR\fprocess_time\x12+\n" +
	"\x04Data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04dataB\vZ\t.;runtimeb\x06proto3"

var (
	file_status_proto_rawDescOnce sync.Once
	file_status_proto_rawDescData []byte
)

func file_status_proto_rawDescGZIP() []byte {
	file_status_proto_rawDescOnce.Do(func() {
		file_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)))
	})
	return file_status_proto_rawDescData
}

var file_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_status_proto_goTypes = []any{
	(*ResponseSuccess)(nil), // 0: runtime.ResponseSuccess
	(*structpb.Struct)(nil), // 1: google.protobuf.Struct
}
var file_status_proto_depIdxs = []int32{
	1, // 0: runtime.ResponseSuccess.Data:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_status_proto_init() }
func file_status_proto_init() {
	if File_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_status_proto_goTypes,
		DependencyIndexes: file_status_proto_depIdxs,
		MessageInfos:      file_status_proto_msgTypes,
	}.Build()
	File_status_proto = out.File
	file_status_proto_goTypes = nil
	file_status_proto_depIdxs = nil
}
