// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: province.proto

package tbl_province

import (
	"time"
)

// Mysql Table: tbl_province
type ProvinceModel struct {
	Id   int    `gorm:"primary_key;column:id"`
	Name string `gorm:"column:name"`

	CreatedAt *time.Time `gorm:"column:created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at"`
}
