// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: province.proto

package tbl_province

import (
	"github.com/herryg91/cdd/examples/location-api/entity"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

func (r *MysqlDatasource) GetByIds(ids []int) (map[int]entity.Province, error) {
	queryResp := []entity.Province{}
	err := r.db.Table(r.tableName).Where("id in (?)", ids).Find(&queryResp).Error
	if err != nil {
		return map[int]entity.Province{}, err
	}
	result := map[int]entity.Province{}
	for _, r := range queryResp {
		result[r.Id] = r
	}
	return result, nil
}
