// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: city.proto

package crud_tbl_city

import "errors"

var ErrDatabaseError = errors.New("Database Error")
var ErrRecordNotFound = errors.New("Record Not Found")
