// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: city.proto

package crud_tbl_city

import (
	"github.com/herryg91/cdd/examples/location-api/entity"
)

type Repository interface {
	additional_repository
	GetByPrimaryKey(id int) (*entity.City, error)
	GetAll() ([]*entity.City, error)
	Create(in entity.City) (*entity.City, error)
	Update(in entity.City) (*entity.City, error)
	Delete(id int) error
}

type UseCase interface {
	additional_usecase
	GetByPrimaryKey(id int) (*entity.City, error)
	GetAll() ([]*entity.City, error)
	Create(in entity.City) (*entity.City, error)
	Update(in entity.City) (*entity.City, error)
	Delete(id int) error
}

// Please write code below in interface.go
/*
	package crud_tbl_city

	type additional_repository interface{
		// AdditionalFunc1()
		// AdditionalFunc2()
	}

	type additional_usecase interface {
		// AdditionalFunc1()
		// AdditionalFunc2()
	}
*/
