// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: users.proto

package tbl_users

import (
	"time"
)

// Mysql Table: tbl_users
type UserModel struct {
	Id         int    `gorm:"primary_key;column:id"`
	Name       string `gorm:"column:name"`
	ProvinceId int    `gorm:"column:province_id"`

	CreatedAt *time.Time `gorm:"column:created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at"`
}
