// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: city.proto

package tbl_city

import (
	"time"
)

// Mysql Table: tbl_city
type CityModel struct {
	Id         int    `gorm:"primary_key;column:id"`
	ProvinceId int    `gorm:"column:province_id"`
	Name       string `gorm:"column:name"`

	CreatedAt *time.Time `gorm:"column:created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at"`
}
