// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: province.proto

package crud_tbl_province

import "errors"

var ErrDatabaseError = errors.New("Database Error")
var ErrRecordNotFound = errors.New("Record Not Found")
