// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: province.proto
package crud_tbl_province

import (
	"fmt"
	tbl_province_ds "github.com/herryg91/cdd/examples/location-api/drivers/datasource/mysql/tbl_province"
	"github.com/herryg91/cdd/examples/location-api/entity"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type repository struct {
	db *gorm.DB
	ds *tbl_province_ds.MysqlDatasource
}

func NewRepository(db *gorm.DB, ds *tbl_province_ds.MysqlDatasource) Repository {
	return &repository{db, ds}
}
func (r *repository) GetByPrimaryKey(id int) (*entity.Province, error) {
	out, err := r.ds.GetByPrimaryKey(id)
	if err != nil {
		if gorm.IsRecordNotFoundError(err) {
			return nil, ErrRecordNotFound
		}
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out.ToProvinceEntity(), err
}
func (r *repository) GetAll() ([]*entity.Province, error) {
	datas, err := r.ds.GetAll()
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	out := []*entity.Province{}
	for _, data := range datas {
		out = append(out, data.ToProvinceEntity())
	}
	return out, err
}
func (r *repository) Create(in entity.Province) (*entity.Province, error) {
	out, err := r.ds.Create(*tbl_province_ds.ProvinceModel{}.FromProvinceEntity(in))
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out.ToProvinceEntity(), err
}
func (r *repository) Update(in entity.Province) (*entity.Province, error) {
	out, err := r.ds.Update(*tbl_province_ds.ProvinceModel{}.FromProvinceEntity(in))
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out.ToProvinceEntity(), err
}
func (r *repository) Delete(id int) error {
	err := r.ds.Delete(id)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return err
}

/*
	// Add this in drivers/datasource/mysql/tbl_province/{any_file}.go

	func (model *ProvinceModel) ToProvinceEntity() *entity.Province {
		return &entity.Province{
			Id:model.Id,
			Name:model.Name,
		}
	}
	func (ProvinceModel) FromProvinceEntity(in entity.Province) *ProvinceModel {
		return &ProvinceModel{
			Id:in.Id,
			Name:in.Name,
		}
	}
*/
