// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: province.proto
package crud_tbl_province

import (
	"fmt"
	tbl_province_ds "github.com/herryg91/cdd/examples/location-api/drivers/datasource/mysql/tbl_province"
	"github.com/herryg91/cdd/examples/location-api/entity"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type repository struct {
	db *gorm.DB
	ds *tbl_province_ds.MysqlDatasource
}

func NewRepository(db *gorm.DB, ds *tbl_province_ds.MysqlDatasource) Repository {
	return &repository{db, ds}
}
func (r *repository) GetByPrimaryKey(id int) (*entity.Province, error) {
	out, err := r.ds.GetByPrimaryKey(id)
	if err != nil {
		if gorm.IsRecordNotFoundError(err) {
			return nil, ErrRecordNotFound
		}
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out, err
}
func (r *repository) GetAll() ([]*entity.Province, error) {
	out, err := r.ds.GetAll()
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out, err
}
func (r *repository) Create(in entity.Province) (*entity.Province, error) {
	out, err := r.ds.Create(in)
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out, err
}
func (r *repository) Update(in entity.Province) (*entity.Province, error) {
	out, err := r.ds.Update(in)
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out, err
}
func (r *repository) Delete(id int) error {
	err := r.ds.Delete(id)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return err
}
