// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HTTPStatus    int32                  `protobuf:"varint,1,opt,name=HTTPStatus,json=http_status,proto3" json:"HTTPStatus,omitempty"`
	GRPCStatus    int32                  `protobuf:"varint,2,opt,name=GRPCStatus,json=grpc_status,proto3" json:"GRPCStatus,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	OtherErrors   []*ErrorDetail         `protobuf:"bytes,5,rep,name=OtherErrors,json=other_errors,proto3" json:"OtherErrors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetHTTPStatus() int32 {
	if x != nil {
		return x.HTTPStatus
	}
	return 0
}

func (x *Error) GetGRPCStatus() int32 {
	if x != nil {
		return x.GRPCStatus
	}
	return 0
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetOtherErrors() []*ErrorDetail {
	if x != nil {
		return x.OtherErrors
	}
	return nil
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=Field,json=field,proto3" json:"Field,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetail) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\x06errors\"\xaf\x01\n" +
	"\x05Error\x12\x1f\n" +
	"\n" +
	"HTTPStatus\x18\x01 \x01(\x05R\vhttp_status\x12\x1f\n" +
	"\n" +
	"GRPCStatus\x18\x02 \x01(\x05R\vgrpc_status\x12\x12\n" +
	"\x04Code\x18\x03 \x01(\x05R\x04code\x12\x18\n" +
	"\aMessage\x18\x04 \x01(\tR\amessage\x126\n" +
	"\vOtherErrors\x18\x05 \x03(\v2\x13.errors.ErrorDetailR\fother_errors\"Q\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05Field\x18\x02 \x01(\tR\x05field\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\amessageB\n" +
	"Z\b.;errorsb\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_errors_proto_goTypes = []any{
	(*Error)(nil),       // 0: errors.Error
	(*ErrorDetail)(nil), // 1: errors.ErrorDetail
}
var file_errors_proto_depIdxs = []int32{
	1, // 0: errors.Error.OtherErrors:type_name -> errors.ErrorDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		MessageInfos:      file_errors_proto_msgTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
