// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: users.proto

package crud_tbl_users

import "errors"

var ErrDatabaseError = errors.New("Database Error")
var ErrRecordNotFound = errors.New("Record Not Found")
