// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: users.proto
package crud_tbl_users

import (
	"fmt"
	tbl_users_ds "github.com/herryg91/cdd/examples/users-api/drivers/datasource/mysql/tbl_users"
	"github.com/herryg91/cdd/examples/users-api/entity"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type repository struct {
	db *gorm.DB
	ds *tbl_users_ds.MysqlDatasource
}

func NewRepository(db *gorm.DB, ds *tbl_users_ds.MysqlDatasource) Repository {
	return &repository{db, ds}
}
func (r *repository) GetByPrimaryKey(id int) (*entity.User, error) {
	out, err := r.ds.GetByPrimaryKey(id)
	if err != nil {
		if gorm.IsRecordNotFoundError(err) {
			return nil, ErrRecordNotFound
		}
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out.ToUserEntity(), err
}
func (r *repository) GetAll() ([]*entity.User, error) {
	datas, err := r.ds.GetAll()
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	out := []*entity.User{}
	for _, data := range datas {
		out = append(out, data.ToUserEntity())
	}
	return out, err
}
func (r *repository) Create(in entity.User) (*entity.User, error) {
	out, err := r.ds.Create(*tbl_users_ds.UserModel{}.FromUserEntity(in))
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out.ToUserEntity(), err
}
func (r *repository) Update(in entity.User) (*entity.User, error) {
	out, err := r.ds.Update(*tbl_users_ds.UserModel{}.FromUserEntity(in))
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return out.ToUserEntity(), err
}
func (r *repository) Delete(id int) error {
	err := r.ds.Delete(id)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrDatabaseError, err.Error())
	}
	return err
}

/*
	// Add this in drivers/datasource/mysql/tbl_users/{any_file}.go

	func (model *UserModel) ToUserEntity() *entity.User {
		return &entity.User{
			Id:model.Id,
			Name:model.Name,
			ProvinceId:model.ProvinceId,
		}
	}
	func (UserModel) FromUserEntity(in entity.User) *UserModel {
		return &UserModel{
			Id:in.Id,
			Name:in.Name,
			ProvinceId:in.ProvinceId,
		}
	}
*/
