// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: users.proto

package crud_tbl_users

import (
	"github.com/herryg91/cdd/examples/users-api/entity"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type usecase struct {
	repo Repository
}

func NewUsecase(repo Repository) UseCase {
	return &usecase{
		repo: repo,
	}
}

func (uc *usecase) GetByPrimaryKey(id int) (*entity.User, error) {
	return uc.repo.GetByPrimaryKey(id)
}

func (uc *usecase) GetAll() ([]*entity.User, error) {
	return uc.repo.GetAll()
}

func (uc *usecase) Create(in entity.User) (*entity.User, error) {
	return uc.repo.Create(in)
}

func (uc *usecase) Update(in entity.User) (*entity.User, error) {
	return uc.repo.Update(in)
}

func (uc *usecase) Delete(id int) error {
	return uc.repo.Delete(id)
}
